apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-inspector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-inspector.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "plugin-inspector.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
